# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DDOCTEST_CONFIG_NO_EXCEPTIONS

CXX_INCLUDES = -I/mnt/c/Users/narut/OneDrive/Desktop/Project/techbots_Sumo_Robots/host/../src -isystem /mnt/c/Users/narut/OneDrive/Desktop/Project/techbots_Sumo_Robots/host/third_party

CXX_FLAGS = -fsanitize=address,undefined -fno-omit-frame-pointer -fno-pie -g -std=c++17 -Wall -Wextra -Wpedantic -Werror -fno-exceptions -fno-rtti

